# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 20:17
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=256)),
                ('heading', models.CharField(blank=True, max_length=256)),
                ('encoding', models.CharField(blank=True, max_length=256)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2016, 7, 16, 23, 17, 2, 333216))),
                ('updated_on', models.DateTimeField(default=datetime.datetime(2016, 7, 16, 23, 17, 2, 333255))),
                ('results', models.CharField(blank=True, max_length=128)),
                ('job_id', models.CharField(max_length=128)),
            ],
        ),
    ]
