# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 20:17
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceurl',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 16, 23, 17, 13, 52676)),
        ),
        migrations.AlterField(
            model_name='sourceurl',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 16, 23, 17, 13, 52714)),
        ),
    ]
