# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160716_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourceurl',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterField(
            model_name='sourceurl',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sourceurl',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
