# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160717_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourceurl',
            options={'ordering': ['-created_on']},
        ),
    ]
